// 4권 × 12과 커리큘럼 플랜 (공유 데이터)
export const CURRICULUM_PLAN = {
  생각: [
    { lesson: 1,  theme: '마음의 변화: 4차원의 영성이란',    scripture: '롬 12:2' },
    { lesson: 2,  theme: '생각의 힘과 성경적 근거',          scripture: '빌 4:8' },
    { lesson: 3,  theme: '긍정적 사고의 능력',               scripture: '잠 23:7' },
    { lesson: 4,  theme: '두려움을 이기는 마음',             scripture: '딤후 1:7' },
    { lesson: 5,  theme: '성령으로 새로워지는 마음',         scripture: '엡 4:23' },
    { lesson: 6,  theme: '역경 속 긍정의 비밀',              scripture: '롬 8:28' },
    { lesson: 7,  theme: '하나님의 눈으로 보기',             scripture: '민 13:30' },
    { lesson: 8,  theme: '생각이 바뀐 사람들의 이야기',      scripture: '히 11:27' },
    { lesson: 9,  theme: '매일 마음 새롭게 하는 훈련',       scripture: '시 19:14' },
    { lesson: 10, theme: '부정적 생각 패턴 극복',            scripture: '고후 10:5' },
    { lesson: 11, theme: '감사와 찬양으로 생각 훈련',        scripture: '살전 5:18' },
    { lesson: 12, theme: '변화된 마음으로 사는 삶',          scripture: '롬 12:2' },
  ],
  믿음: [
    { lesson: 1,  theme: '믿음이란 무엇인가',                scripture: '히 11:1' },
    { lesson: 2,  theme: '믿음의 실체와 증거',               scripture: '막 11:24' },
    { lesson: 3,  theme: '하나님 약속을 붙드는 믿음',        scripture: '민 23:19' },
    { lesson: 4,  theme: '믿음과 행함',                      scripture: '약 2:17' },
    { lesson: 5,  theme: '시험을 통해 자라는 믿음',          scripture: '약 1:3' },
    { lesson: 6,  theme: '기도의 믿음',                      scripture: '막 11:23' },
    { lesson: 7,  theme: '기적을 일으키는 믿음',             scripture: '마 17:20' },
    { lesson: 8,  theme: '믿음으로 산 사람들',               scripture: '히 11:8' },
    { lesson: 9,  theme: '일상에서 믿음 훈련',               scripture: '갈 2:20' },
    { lesson: 10, theme: '의심을 극복하는 믿음',             scripture: '마 14:31' },
    { lesson: 11, theme: '공동체 안에서 믿음 세우기',        scripture: '살전 5:11' },
    { lesson: 12, theme: '믿음의 완성: 소망과 인내',         scripture: '히 12:2' },
  ],
  꿈: [
    { lesson: 1,  theme: '하나님이 주시는 꿈이란',           scripture: '잠 29:18' },
    { lesson: 2,  theme: '꿈의 성경적 근거',                 scripture: '요엘 2:28' },
    { lesson: 3,  theme: '하나님의 목적을 발견하기',         scripture: '렘 29:11' },
    { lesson: 4,  theme: '꿈을 품고 사는 힘',               scripture: '합 2:2' },
    { lesson: 5,  theme: '역경 속에서 꿈 지키기',            scripture: '창 37:19' },
    { lesson: 6,  theme: '꿈을 이루는 믿음의 과정',          scripture: '창 41:39' },
    { lesson: 7,  theme: '공동체의 꿈, 함께 이루는 비전',   scripture: '느 2:17' },
    { lesson: 8,  theme: '꿈으로 산 사람들',                 scripture: '행 2:17' },
    { lesson: 9,  theme: '꿈을 명확하게 하는 훈련',          scripture: '빌 3:14' },
    { lesson: 10, theme: '꿈을 향한 구체적 계획',            scripture: '눅 14:28' },
    { lesson: 11, theme: '포기하지 않는 꿈의 훈련',          scripture: '갈 6:9' },
    { lesson: 12, theme: '꿈의 성취와 하나님께 영광',        scripture: '시 37:4' },
  ],
  말: [
    { lesson: 1,  theme: '말의 능력: 4차원의 영성과 언어',   scripture: '잠 18:21' },
    { lesson: 2,  theme: '말이 창조하는 힘',                 scripture: '창 1:3' },
    { lesson: 3,  theme: '믿음의 고백이란',                  scripture: '롬 10:10' },
    { lesson: 4,  theme: '선포하는 삶',                      scripture: '막 11:23' },
    { lesson: 5,  theme: '부정적 언어를 극복하는 말',        scripture: '엡 4:29' },
    { lesson: 6,  theme: '치유와 회복을 가져오는 말',        scripture: '잠 12:18' },
    { lesson: 7,  theme: '공동체를 세우는 말',               scripture: '엡 4:15' },
    { lesson: 8,  theme: '말로 역사한 믿음의 사람들',        scripture: '수 6:16' },
    { lesson: 9,  theme: '매일 선포하는 말 훈련',            scripture: '시 19:14' },
    { lesson: 10, theme: '혀를 다스리는 훈련',               scripture: '약 3:5' },
    { lesson: 11, theme: '중보기도와 선포하는 기도',         scripture: '사 45:11' },
    { lesson: 12, theme: '말의 사람으로 살아가기',           scripture: '골 4:6' },
  ],
};
